# Generated by Django 2.0.3 on 2018-04-11 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Past_Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Company_Role', models.CharField(max_length=100)),
                ('Work_Status', models.CharField(max_length=100)),
                ('Image', models.ImageField(upload_to='')),
                ('Video', models.FileField(upload_to='')),
                ('From_Duration', models.DateField()),
                ('To_Duration', models.DateField()),
            ],
        ),
    ]
